### ISSUE TITLE
Add mv/mh/pv/ph

### ISSUE THREAD

**Issue by mxstbr** [rebassjs/rebass#509]
I have a hard time remembering which axis is X and which is Y, I tend to always choose the wrong one, making `mx` and `my` a minefield. 😅 

It'd be awesome if Rebass had support for `mv` (margin vertical) and `mh` (margin horizontal), as well as the equivalent padding props. That I definitely won't mess up.

**Comment by jxnblk** [comment]
You can always wrap the component to map props however you want, but I've always leaned towards the x-axis and y-axis shorthand, since that's the same as most CSS properties (e.g. `translateX`).

This does make me curious though, aren't x-axis and y-axis sort of international (i.e. not English-only) conventions?

**Comment by mxstbr** [comment]
> aren't x-axis and y-axis sort of international (i.e. not English-only) conventions?

Yes, I just can't remember them 🙈 

Will close!
