### ISSUE TITLE
Typescript definitions for onClick etc.

### ISSUE THREAD

**Issue by zerocity** [rebassjs/rebass#528]
Hi, 

if have problems with the typings. 

You can't use onClick or others standard props on Box etc. 
If you use styled-components you get this typing. 

This is my intermediate fix to get additional type information

```tsx
export interface ExtendedBox extends BoxProps {
    onClick?: () => {}
}

export const Box: React.SFC<ExtendedBox> = props => <BaseBox {...props} />

**Comment by jxnblk** [comment]
You shouldn’t need type definitions for built-in React props, should you?

**Comment by j-em** [comment]
I would say this is a problem for me as well.

It's my understanding that you can get accurate type checking while using styled-components because the library is typed in terms of the `JSX.IntrinsicElements` interface while rebass is not.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/fe3bb114a3203f058d8bffedc996c92712609275/types/styled-components/index.d.ts#L100

**Comment by twop** [comment]
Same for me. Although I'm not 100% that Button & Box should allow entire set of dom props + It would mess up with intellisense

<img width="715" alt="image" src="https://user-images.githubusercontent.com/6633216/48974350-aeee6b80-f00a-11e8-85f0-42887288e492.png">

**Comment by jxnblk** [comment]
Closing this out since this seems like an issue with typescript, and Rebass is not written with TS

**Comment by chuckdries** [comment]
I've got a PR out for @types/rebass to fix this, but I'm still a bit of a novice. If anyone in this thread would like to take a look, I'd really appreciate it. This change has solved my onClick issues for now, but maybe introduced an issue with doing `styled(rebassComponent)<componentProps>`?

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32565

To test it:
