### ISSUE TITLE
Themed button not respecting padding prop

### ISSUE THREAD

**Issue by steverecio** [rebassjs/rebass#546]
Themed button component isn't respecting the padding prop. Margin prop is being rendered properly but not padding.

### Theme.js
`
buttons: {
        primary: {
            font: text_font,
            color: light_grey,
            border: '1px solid white',
            cursor: 'pointer',
            transition: 'opacity 0.15s ease-in-out',
            '&:hover': {
                opacity: 0.5
            }
        }
}
`

### Component Definition

`
<Button variant='primary' p={3} mr={50}>Submit</Button>
`

**Comment by jxnblk** [comment]
Hey how's it going 👋 

The Button component has default props for `px` and `py` (https://github.com/rebassjs/rebass/blob/master/src/index.js#L141-L142), and because `p` is the CSS shorthand property `padding`, the `px` and `py` props are overriding that one – it's definitely a little confusing, but I opted to have the margin and padding props more closely follow CSS than try to do anything fancy

**Comment by steverecio** [comment]
Ohh... ok cool. Yeah now I'm able to make it work by overriding `px` and `py` instead of using `p`. Thanks Jackson! 🥇
