### ISSUE TITLE
No license found in @rebass/emotion

### ISSUE THREAD

**Issue by edmundas-ramanauskas** [rebassjs/rebass#588]
Could you add a license for @rebass/emotion package?

**Comment by jxnblk** [comment]
It's under the same license as everything else in this repo https://github.com/rebassjs/rebass/blob/master/LICENSE.md – I would accept a PR adding a field to the `package.json` if it's missing

**Comment by edmundas-ramanauskas** [comment]
@jxnblk https://github.com/rebassjs/rebass/pull/589

**Comment by codepunkt** [comment]
This alone is not sufficient. In order to use open source licensed as MIT, one must adhere to the attribution rules of that license - which requires to include the license text _with_ copyright when redistributing.

TLDR: Every module published to npm needs an SPDX license identifier in the `license` field in `package.json` (done in the PR) and a `LICENSE` or similarly named file in the project root that includes a matching license text (without any changes) and the appropriate copyright filled in.

**Comment by edmundas-ramanauskas** [comment]
made another PR with license file added

**Comment by edmundas-ramanauskas** [comment]
from my perspective I consider this issue as resolved. @jxnblk you can close it.

**Comment by jxnblk** [comment]
Thanks for helping out with this!
