### ISSUE TITLE
propTypes not being inherited

### ISSUE THREAD

**Issue by woro83c** [rebassjs/rebass#592]
I just noticed the Flex component doesn't inherit propTypes from the Box component, which is what it extends from. Is this intended?

**Comment by jxnblk** [comment]
The Flex component *should* render the Box component, which means props types will be checked on the Box component and aren't needed since they aren't props for Flex. This is how React *should* work, but I know that styled-components changed the behavior of how extending components works internally, and (if you're noticing strange behavior) there might be bugs in their implementation
