### ISSUE TITLE
Variant override problem

### ISSUE THREAD

**Issue by kwiss** [rebassjs/rebass#634]
Hey guys,

i'm trying to extend text component and a create variant 

my extend is :
```
import {Text as RebassText} from 'rebass';

const baseStyle = {
  fontWeight: 500,
  color: 'text',
  fontSize: 1
};

export const Text = (props) => {
  return <RebassText {...props}  sx={baseStyle} />;
};
```

my variant is :
```
color: {
  text: '#404040',
  textSecondary: '#6A6A6A',
}

text: {
    secondary: {
      fontSize: 3
      color: 'textSecondary',
    },
}
```

but extended component color and fontSize override variant is this the normal behavior ?
am i doing something wrong somewhere ?

here is the generated style :

```diff
    box-sizing: border-box;
    margin: 0;
    min-width: 0;
-   color: #6A6A6A;
-   font-size: 18px;
    font-weight: 500;
+   color: #404040;
+   font-size: 14px;
```

**Comment by jxnblk** [comment]
Sorry, still working on some of the docs around this. The `sx` prop takes precedence over variants. If you want to change a CSS property based on a variant, I'd recommend setting that in a default variant instead of the `sx` prop. In general, I'd say try to avoid mixing conflicting styles across the variants, `sx` prop, and style props, because mixing them is likely to cause unexpected results

```js
// example theme
text: {
  base: {
    fontSize: 2,
  },
  secondary: {
    fontSize: 3,
  },
}
```

```jsx
const CustomText = props =>
  <Text
    variant='default'
    {...props}
  />
```

**Comment by kwiss** [comment]
thanks @jxnblk for that quick anwser, i'll check that way
